spring.application.name=shoes_store
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html

# Cấu hình MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/namda?useSSL=false&serverTimezone=UTC&allowZeroDateTime=true&convertToNull=truespring.datasource.username=root
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Cấu hình upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Đường dẫn upload (tùy chọn)
upload.path=uploads

API_KEY=NAMthaykeygroqvao
#VNPay
vnpay.TmnCode=5EMOND1T
#vnpay.secretKey=8SSKHMNVIVYJ2VUVR7TM42ILG1F44F3R
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.returnUrl=https://master-filly-mostly.ngrok-free.app/api/v1/payment/vnpay-return
#vnpay.returnUrl=https://master-filly-mostly.ngrok-free.app/bookingBE-MNC/api/v1/payment/vnpay_return
#vnpay.returnUrl=http://localhost:5173/thank-you

# Return URL phải trỏ về BACKEND, không phải Frontend
vnpay.returnUrl= http://localhost:8080/vnpay-payment-result
secretKey=W6PGSYV9VKDBGCKXPJ0WN7GQ494H4A8Y
# Thêm IPN URL (quan trọng)
vnpay.ipnUrl=http://localhost:8080/api/vnpay/vnpay_ipn
#vnpay.returnUrl=http://localhost:5000/bookingBE-MNC/api/v1/payment/vnpay_return